### ISSUE TITLE
several IBM onesided tests are failing with sessions prototype

### ISSUE THREAD

**Issue by hppritcha** [hpc/ompi#25]
FAIL: c_create_no_free
FAIL: c_lock_negative_rank
FAIL: c_accumulate_ddt1
FAIL: mt_1sided <--------------------- hangs
FAIL: c_reqops
FAIL: ring_1sided_mpifh
FAIL: ring_1sided_usempi
FAIL: ring_1sided_sync_reg_usempi

most of the failures exhibit a segfault, but in different places.  mt_1sided hangs.

**Comment by hjelmn** [comment]
Might need to be synced with master. I will take a look tomorrow. Setting some time aside for ompi stuff.

**Comment by hppritcha** [comment]
a rebase - which took a LOT of work - on top of master (3078485) - all but one one sided now pass.  c_transpose6 still fails.

**Comment by hppritcha** [comment]
after today's rebase, only c_transpose6 fails.  Closing this issue and opening a new one specific to odd MPI_COMM_SELF RMA behavior.
