### ISSUE TITLE
Sessions prototype has an issue with using MPI_COMM_SELF for RMA windows

### ISSUE THREAD

**Issue by hppritcha** [hpc/ompi#32]
The ibm/onesided/c_transpose6 and ibm/random/attr-error-code tests fail with this signature when using the Sessions prototype:
```
Running test
Running test: mpirun -np 4 ./c_transpose6
[st-master:00000] *** An error occurred in MPI_Win_create
[st-master:00000] *** reported by process [942407681,281470681743360]
[st-master:00000] *** on communicator MPI_COMM_SELF
[st-master:00000] *** MPI_ERR_WIN: invalid window
[st-master:00000] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[st-master:00000] ***    and potentially your MPI job)
```

**Comment by hjelmn** [comment]
hmm, are you going to look at this? I am planning on testing some osc changes on trinitite today or tomorrow. I can look at this then if you want.

**Comment by hppritcha** [comment]
turns out this is observed on master.  related to removal of the OSC PT2PT component.

**Comment by hppritcha** [comment]
closing as not directly relevant to the sessions prototoype.
