### ISSUE TITLE
new failures after rebase of sessions prototype on top of ompi master commit 5de8af8f

### ISSUE THREAD

**Issue by hppritcha** [hpc/ompi#38]
IBM test failures of prototype prior to rebase:

```
FAIL: spawn_with_env_vars
FAIL: no-disconnect
FAIL: intercomm_create
FAIL: c_transpose6
FAIL: c_get_accumulate_ddt1
FAIL: c_get_accumulate_ddt2
FAIL: c_get_accumulate_ddt3
FAIL: handle_check_f08
FAIL: attr-error-code
```
but after the rebase more failures are observed
```
FAIL: op
FAIL: reduce_scatter_block_nocommute_stride_in_place
FAIL: reduce_scatter_block_nocommute_stride
FAIL: op_mpifh
FAIL: op_usempi
FAIL: op_usempif08
FAIL: aint
FAIL: aint_mpifh
FAIL: aint_usempif08
FAIL: aint_usempi
FAIL: spawn_with_env_vars
FAIL: intercomm_create
FAIL: err
FAIL: c_create_disp
FAIL: c_create_info
FAIL: c_create_no_free
FAIL: c_win_attr
FAIL: c_create
FAIL: c_create_size
FAIL: c_fence_lock
FAIL: c_create_info_half
FAIL: c_win_errhandler
FAIL: c_fence_simple
FAIL: c_fence_put_1
FAIL: c_fence_asserts
FAIL: c_put
FAIL: c_lock_illegal
FAIL: c_put_big
FAIL: c_put_dynamic_self
FAIL: c_put_self
FAIL: c_accumulate
FAIL: c_accumulate_atomic
FAIL: c_accumulate_ddt1
FAIL: c_accumulate_ddt3
FAIL: c_accumulate_ddt2
FAIL: c_accumulate_ddt4
FAIL: c_get
FAIL: c_get_big
FAIL: c_get_dynamic_self
FAIL: c_get_self
FAIL: c_transpose1
FAIL: c_transpose2
FAIL: c_transpose3
FAIL: c_transpose5
FAIL: c_transpose6
FAIL: c_transpose7
FAIL: c_strided_acc_indexed
FAIL: c_strided_acc_subarray
FAIL: c_strided_acc_onelock
FAIL: c_strided_putget_indexed
FAIL: c_post_start
FAIL: c_strided_get_indexed
FAIL: win_dup_fn
FAIL: pp_1sided
FAIL: 1sided
FAIL: mt_1sided
FAIL: small_1sided
FAIL: multiple_locks2
FAIL: c_fetch_and_op
FAIL: c_flush
FAIL: c_get_accumulate
FAIL: c_get_accumulate_strided
FAIL: c_get_accumulate_ddt1
FAIL: c_get_accumulate_ddt2
FAIL: c_reqops
FAIL: c_strided_getacc_indexed
FAIL: halo_1sided_put_alloc_mem
FAIL: c_create_dynamic
FAIL: compare_and_swap
FAIL: ring_1sided_mpifh
FAIL: win_attr_mpifh
FAIL: win_dup_fn_mpifh
FAIL: ring_1sided_sync_reg_mpifh
FAIL: win_attr_usempi
FAIL: win_dup_fn_usempi
FAIL: halo_1sided_put_alloc_mem_usempi
FAIL: ring_1sided_usempi
FAIL: ring_1sided_sync_reg_usempi
FAIL: win_create_dynamic_usempi
FAIL: win_attr_usempif08
FAIL: halo_1sided_put_alloc_mem_usempif08
FAIL: ring_1sided_usempif08
FAIL: win_create_dynamic_usempif08
FAIL: win_dup_fn_usempif08
FAIL: c_lock_negative_rank
FAIL: handle_check_f08
FAIL: attr-error-code
```
The rebased prototype is on branch ```sessions_new_rebase_on_5de8af8f``` in this repo.

**Comment by hppritcha** [comment]
@tomhers if you could look at the one sided failures - the ones in the onesided folder - i'll start with the collective failures and the fortran failures.

**Comment by hppritcha** [comment]
I'm seeing failures with
```
*** Error in `./reduce_scatter_block_nocommute_stride': free(): invalid next size (normal): 0x000000002a0f2af0 ***
```
and the in_place variant on master

**Comment by hppritcha** [comment]
The ```op_mpifh``` and related tests also fail with master.

**Comment by hjelmn** [comment]
Ugh. Wonder what changed on master that caused Fortran to fail.

**Comment by hppritcha** [comment]
@tomhers since it looks like all (or almost all) failures outside of one-sided I've started investigating.  looks like btl setup got busted in the rebase.

**Comment by tomhers** [comment]
@hppritcha The tests that failed before changing the == to != in osc_rdma_component.c in the prototype were:
c_create_no_free
c_lock_negative_rank
c_transpose3
ring_1sided_mpifh
ring_1sided_sync_reg_mpifh
ring_1sided_usempi
ring_1sided_sync_reg_usempi
ring_1sided_usempif08

The tests that failed after the change were:
c_create_no_free
c_lock_negative_rank
c_strided_getacc_indexed_shared
win_allocate_shared
ring_1sided_mpifh
ring_1sided_sync_reg_mpifh
ring_1sided_usempi
ring_1sided_sync_reg_usempi
win_allocate_usempif08
ring_1sided_usempif08

And the tests that failed on master were:
c_lock_illegal
c_transpose7
win_allocate_usempi

I will investigate the failures that I am getting in the prototype but not in master.

**Comment by hppritcha** [comment]
For me using just sm and self btls - what one gets without ofi or ucx on the USRC cluster - I get these failures:

FAIL: c_create_no_free
FAIL: c_lock_negative_rank
FAIL: c_transpose6
FAIL: c_get_accumulate_ddt1
FAIL: c_get_accumulate_ddt2
FAIL: c_get_accumulate_ddt3
FAIL: ring_1sided_mpifh
FAIL: ring_1sided_sync_reg_mpifh
FAIL: ring_1sided_usempi
FAIL: ring_1sided_sync_reg_usempi
FAIL: ring_1sided_usempif08

master with the change:
FAIL: c_transpose6

master without the change gives the following failures:
FAIL: c_create
FAIL: c_create_size
FAIL: c_create_disp
FAIL: c_create_info
FAIL: c_create_info_half
FAIL: c_create_no_free
FAIL: c_fence_lock
FAIL: c_win_attr
FAIL: c_win_errhandler
FAIL: c_fence_simple
FAIL: c_fence_asserts
FAIL: c_fence_put_1
FAIL: c_lock_illegal
FAIL: c_put
FAIL: c_put_big
FAIL: c_put_dynamic_self
FAIL: c_put_self
FAIL: c_accumulate
FAIL: c_accumulate_atomic
FAIL: c_accumulate_ddt1
FAIL: c_accumulate_ddt2
FAIL: c_accumulate_ddt3
FAIL: c_accumulate_ddt4
FAIL: c_get
FAIL: c_get_big
FAIL: c_get_dynamic_self
FAIL: c_get_self
FAIL: c_transpose1
FAIL: c_transpose2
FAIL: c_transpose3
FAIL: c_transpose6
FAIL: c_transpose5
FAIL: c_transpose7
FAIL: c_strided_acc_indexed
FAIL: c_strided_acc_subarray
FAIL: c_strided_acc_onelock
FAIL: c_strided_get_indexed
FAIL: c_strided_putget_indexed
FAIL: c_post_start
FAIL: win_dup_fn
FAIL: pp_1sided
FAIL: 1sided
FAIL: mt_1sided
FAIL: small_1sided
FAIL: multiple_locks2
FAIL: c_fetch_and_op
FAIL: c_flush
FAIL: c_get_accumulate
FAIL: c_get_accumulate_strided
FAIL: c_get_accumulate_ddt1
FAIL: c_get_accumulate_ddt2
FAIL: c_reqops
FAIL: c_strided_getacc_indexed
FAIL: halo_1sided_put_alloc_mem
FAIL: c_create_dynamic
FAIL: compare_and_swap

**Comment by hppritcha** [comment]
@tomhers I'll take a look at the fortran ones if you want.

**Comment by hppritcha** [comment]
The ring tests are failing as a result of not calling explicit MPI_Win_frees before finalize.  There's something in the prototype's tear down procedure now that results in the barrier inside the internal version of mpi_win_free to blow up in add procs.

**Comment by hppritcha** [comment]
pushed a fix for the ring problems to head of the branch - see d7f756d
with this fix the remaining one-sided failing for me are
```
FAIL: c_transpose6
FAIL: c_get_accumulate_ddt1
FAIL: c_get_accumulate_ddt2
FAIL: c_get_accumulate_ddt3
```
c_transpose6 also fails on master

**Comment by hppritcha** [comment]
@tomhers is working on c_transpose6.  It looks like the get_accumulate using derived data type tests (c_get_accumulate_ddt1, etc.) may be addressed by a commit 3ccf7e3 on master.

**Comment by hjelmn** [comment]
Yes. I would rebase on master again to get the osc/rdma fixes.

**Comment by tomhers** [comment]
@hppritcha Here are the tests still failing after our fix for the attribute subsytem. Let me know if these errors are expected and I will push my changes:
FAIL: op
FAIL: reduce_scatter_block_nocommute_stride
FAIL: reduce_scatter_block_nocommute_stride_in_place
FAIL: op_mpifh
FAIL: op_usempi
FAIL: op_usempif08
FAIL: intercomm
FAIL: spawn
FAIL: spawn_with_env_vars
FAIL: spawn_multiple
FAIL: loop_spawn
FAIL: no-disconnect
FAIL: intercomm_create
FAIL: err
FAIL: attr-error-code

**Comment by hppritcha** [comment]
@tomhers this looks much better.  When using the OB1 PML and at 0ab304f  on the sessions_new_rebase_on_5de8af8f I'm seeing close to this, but the tests also fail on master:

FAIL ON MASTER at c30a716
```
FAIL: op
FAIL: reduce_scatter_block_nocommute_stride
FAIL: reduce_scatter_block_nocommute_stride_in_place
FAIL: op_mpifh
FAIL: op_usempi
FAIL: op_usempif08
FAIL: spawn_with_env_vars
FAIL: c_transpose6
FAIL: c_get_accumulate_ddt1
FAIL: c_get_accumulate_ddt2
FAIL: c_get_accumulate_ddt3
FAIL: handle_check_f08
FAIL: attr-error-code
```
same tests fail with the prototype at the above noted sha.  no additional failures.

We know the intercomm failure is intermittent and we'll need to eventually fix that.  It was also failing periodically before the rebase.   Also let's ignore the spawn failures for now.

Please go ahead and push your fixes to the attribute subsystem to the  sessions_new_rebase_on_5de8af8f branch then I'll move back onto sessions_new.

**Comment by hppritcha** [comment]
closing.  We'll open a new issue once we do another rebase 😸
