### ISSUE TITLE
sessions: need to enforce isolation of objects derived from different sessions

### ISSUE THREAD

**Issue by tomhers** [hpc/ompi#69]
A check needs to be added to any function that operates on multiple communicators to ensure that objects from different sessions are not intermixed in a single MPI procedure call. This can be done by comparing the instance field in the two comm structs, e.g.,

```
if (comm1->instance != comm2->instance) {
        printf("Tried to compare two comms from different sessions\n");
        return OMPI_ERR_BAD_PARAM;
    }
```

Such a check must also be added to MPI procedure calls that take an array of MPI_Request objects as input to ensure that requests from different sessions are not included in the same call. These functions are: MPI_Waitall(), MPI_Waitsome(), MPI_Waitany(), MPI_Testall(), MPI_Testsome(), and MPI_Testany().

**Comment by hppritcha** [comment]
addressed by commit 7db5a887508d838c1dcd377a540b97fcc7504194
